# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [develop]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_KAKAO_KEY=$REACT_APP_KAKAO_KEY" >> .env.production
          echo "REACT_APP_REST_API_KEY=$REACT_APP_REST_API_KEY" >> .env.production
        env:
          REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }}
          REACT_APP_REST_API_KEY: ${{ secrets.REACT_APP_REST_API_KEY }}

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          CI: "" # 경고를 에러로 보지 않게 함
          env:
            REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }}
            REACT_APP_REST_API_KEY: ${{ secrets.REACT_APP_REST_API_KEY }}

      - name: Deploy S3 # Upload build file to S3
        run: |
          aws s3 cp \
            --recursive \
            --region us-west-2 \
            build s3://yaneogal.site
